### ISSUE TITLE
The cursorStyle is not having any effect on the page. 

### ISSUE THREAD

**Issue by Lowell20** [Wykks/ngx-mapbox-gl#409]
Using Angular 16, "ngx-mapbox-gl": "10.0.0"

The cursorStyle is not having any effect on the page. 

I would expect the cursor to be a pointer when mousing over the map.
Please let me know if it is possible to use an image in place of 'pointer'
>     
<mgl-map
      [style]="mapStyle"
      [zoom]="[zoom]"
      [bearing]="[0]"
      [pitch]="[45]"
      [center]="center"
      [style.height.%]="100"
      [cursorStyle]="'pointer'"
      (mapClick)="onMapClick($event)"
    >

**Comment by danielkuhlwein** [comment]
I am reproducing the same issue.

Angular: "18.2.1"
ngx-mapbox-gl: "11.0.1"

Passing any valid cursor attribute into `mgl-map` component's `cursorStyle` property is not having any effect. It also throws this error:

```bash
TypeError: Cannot read properties of undefined (reading 'getCanvasContainer')
    at _MapService.changeCanvasCursor (ngx-mapbox-gl.mjs:204:37)
    at _MapComponent.ngAfterViewInit (ngx-mapbox-gl.mjs:2472:23)
    at callHookInternal (core.mjs:5007:10)
    at callHook (core.mjs:5031:7)
    at callHooks (core.mjs:4991:9)
    at executeInitAndCheckHooks (core.mjs:4946:5)
    at refreshView (core.mjs:13413:11)
    at detectChangesInView (core.mjs:13549:5)
    at detectChangesInViewIfAttached (core.mjs:13511:3)
    at detectChangesInComponent (core.mjs:13500:3)
```
